"""Self-contained HTML report generator for audit results."""

from __future__ import annotations

import html
from pathlib import Path
from typing import Any

from shared.report_css import REPORT_CSS
from shared.types import CategoryResult, CheckResult, FullReport, MultiPageReport

REPORT_FILE = "report.html"
INDEX_FILE = "index.html"
MAX_DETAIL_ITEMS = 10
FOOTER = "Generated by seo-geo-automation (MIT License)"
SEVERITY_COLORS = {
    "PASS": "#15803d",
    "WARN": "#b45309",
    "FAIL": "#b91c1c",
    "INFO": "#1d4ed8",
    "ERROR": "#991b1b",
}
SEVERITY_ICONS = {
    "PASS": "&#10004;",
    "WARN": "&#9888;",
    "FAIL": "&#10008;",
    "INFO": "&#8505;",
    "ERROR": "&#9760;",
}


def _escape(text: object) -> str:
    return html.escape(str(text))


def _severity_badge(sev: str) -> str:
    color = SEVERITY_COLORS.get(sev, "#4b5563")
    icon = SEVERITY_ICONS.get(sev, "")
    return f'<span class="badge" style="background:{color}">{icon} {sev}</span>'


def _detail_value(value: Any) -> str:
    if isinstance(value, list):
        text = "<br>".join(_escape(item) for item in value[:MAX_DETAIL_ITEMS])
        extra = len(value) - MAX_DETAIL_ITEMS
        return text + (f"<br><em>... and {extra} more</em>" if extra > 0 else "")
    if isinstance(value, dict):
        return "<br>".join(f"{_escape(k)}: {_escape(v)}" for k, v in value.items())
    return _escape(value)


def _render_details(details: dict[str, Any]) -> str:
    if not details:
        return ""
    rows = "".join(
        f"<tr><td class='detail-key'>{_escape(k)}</td><td>{_detail_value(v)}</td></tr>"
        for k, v in details.items()
    )
    return f"<table class='details'>{rows}</table>"


def _render_check(check: CheckResult) -> str:
    return (
        f'<div class="check check-{check.severity.value.lower()}">'
        f'<div class="check-header">{_severity_badge(check.severity.value)}'
        f"<strong>{_escape(check.check_id)}</strong>"
        f'<span class="check-name">{_escape(check.name)}</span></div>'
        f'<div class="check-message">{_escape(check.message)}</div>'
        f"{_render_details(check.details)}</div>"
    )


def _category_id(cat: CategoryResult) -> str:
    return cat.category.lower().replace(" ", "-")


def _render_nav_item(cat: CategoryResult) -> str:
    status = "fail" if cat.fail_count else "warn" if cat.warn_count else "pass"
    return (
        f'<a href="#{_category_id(cat)}" class="nav-{status}">{_escape(cat.category)} '
        f"{cat.pass_count}/{len(cat.checks)}</a>"
    )


def _render_category(cat: CategoryResult) -> str:
    counts = (
        f'<span class="cat-pass">{cat.pass_count} PASS</span> '
        f'<span class="cat-warn">{cat.warn_count} WARN</span> '
        f'<span class="cat-fail">{cat.fail_count} FAIL</span>'
    )
    checks = "".join(_render_check(c) for c in cat.checks)
    return (
        f'<section id="{_category_id(cat)}" class="category">'
        f"<h2>{_escape(cat.category)} <small>({len(cat.checks)} checks: {counts})</small></h2>"
        f"{checks}</section>"
    )


def _summary_cards(cards: list[tuple[str, int, str]]) -> str:
    items = "".join(
        f'<div class="summary-card"><div class="num {css}">{value}</div>'
        f'<div class="label">{label}</div></div>'
        for label, value, css in cards
    )
    return f'<div class="summary">{items}</div>'


def _page(title: str, body: str) -> str:
    return (
        '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="UTF-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
        f"<title>{_escape(title)}</title>\n<style>{REPORT_CSS}</style>\n</head>\n"
        f'<body>\n<div class="container">{body}<footer>{FOOTER}</footer></div>\n</body>\n</html>\n'
    )


def _ai_section(ai_summary: str | None) -> tuple[str, str]:
    if not ai_summary:
        return "", ""
    section = (
        '<section id="ai-synthesis" class="category ai-section"><h2>AI Synthesis</h2>'
        f'<div class="ai-content"><pre>{_escape(ai_summary)}</pre></div></section>'
    )
    return '<a href="#ai-synthesis" class="nav-ai">AI Synthesis</a>', section


def generate_html_report(report: FullReport, output_dir: Path, ai_summary: str | None = None) -> Path:
    """Write report.html for one audited URL and return its path."""
    ai_nav, ai_html = _ai_section(ai_summary)
    nav = "".join(_render_nav_item(c) for c in report.categories) + ai_nav
    body = (
        f"<header><h1>SEO Audit Report</h1><div class='meta'>{_escape(report.url)}</div>"
        f"<div class='meta'>Generated: {_escape(report.timestamp)}</div></header>"
        + _summary_cards(
            [
                ("Total Checks", report.total_checks, "num-total"),
                ("Passed", report.total_pass, "num-pass"),
                ("Warnings", report.total_warn, "num-warn"),
                ("Failed", report.total_fail, "num-fail"),
            ]
        )
        + f"<nav>{nav}</nav>"
        + "".join(_render_category(c) for c in report.categories)
        + ai_html
    )
    path = output_dir / REPORT_FILE
    path.write_text(_page(f"SEO Audit: {report.domain}", body), encoding="utf-8")
    return path


def _aggregate_row(multi: MultiPageReport, index: int) -> str:
    page = multi.pages[index]
    r = page.report
    status = "fail" if r.total_fail else "warn" if r.total_warn else "pass"
    return (
        f'<tr class="row-{status}"><td><a href="{_escape(page.slug)}/{REPORT_FILE}">'
        f"{_escape(page.slug)}</a></td><td>{_escape(page.page_type)}</td>"
        f"<td>{_escape(page.url)}</td><td>{r.total_checks}</td>"
        f'<td class="cat-pass">{r.total_pass}</td><td class="cat-warn">{r.total_warn}</td>'
        f'<td class="cat-fail">{r.total_fail}</td></tr>'
    )


def generate_aggregate_report(multi: MultiPageReport, output_dir: Path) -> Path:
    """Write index.html linking every per-page report of a multi-page audit."""
    rows = "".join(_aggregate_row(multi, i) for i in range(len(multi.pages)))
    head = "".join(f"<th>{h}</th>" for h in ("Page", "Type", "URL", "Total", "Pass", "Warn", "Fail"))
    body = (
        f"<header><h1>Multi-Page SEO Audit</h1><div class='meta'>{_escape(multi.domain)} - "
        f"{_escape(multi.timestamp)}</div></header>"
        + _summary_cards(
            [
                ("Pages", len(multi.pages), "num-pages"),
                ("Total Checks", multi.total_checks, "num-total"),
                ("Passed", multi.total_pass, "num-pass"),
                ("Warnings", multi.total_warn, "num-warn"),
                ("Failed", multi.total_fail, "num-fail"),
            ]
        )
        + f"<div class='table-wrap'><table class='pages'><thead><tr>{head}</tr></thead>"
        f"<tbody>{rows}</tbody></table></div>"
    )
    path = output_dir / INDEX_FILE
    path.write_text(_page(f"Multi-Page SEO Audit: {multi.domain}", body), encoding="utf-8")
    return path
